### PR TITLE
Postgres test pipeline shared workflow

### PR DESCRIPTION
**Pull request by woodchuck**

### CODE REVIEW

**Comment by woodchuck** [comment]
Used by https://github.com/cuvmit/ezyvet-data-api/pull/1

**Review by ds269 — APPROVED** [review]

**Comment by craig-riecke** [comment]
I don't think this is a good idea because it runs as a separate job from the build/deploy job, thus it must do a bunch of redundant work - i.e. building the project twice.  It should be integrated into the existing NodeJS build steps and turned on with a flag of some sort.  Or something more clever like a Github custom action that can be called as a build step.

**Comment by woodchuck** [comment]
@craig-riecke I looked at making this part of the existing build steps and passing in a flag. I agree that would be ideal. I don't see any way to make the configuration of the postgres service container subject to the flag though. I think the container would get created on every build run, whether it was used or not, and that could drive up costs. Maybe there is a way though, and I just haven't seen it...

**Comment by craig-riecke** [comment]
Yeah it appears services are not flaggable by conditions like steps are.  Which is too bad.  I guess this will do until Github fixes it, which I'm sure will happen in the next year or two.

**Comment by woodchuck** [comment]
I've thought of something I'll play with tomorrow. It might work to nest this whole thing another level below a `uses:` that's within a conditional.

**Review by craig-riecke — APPROVED** [review]

**Comment by woodchuck** [comment]
Crud. After a bunch of trial, and mostly error, I believe the nested approach is currently impossible. The docs say:

> Steps in a job can communicate with all service containers that are part of the same job. However, you cannot create and use service containers inside a composite action. 

But only a composite action can be referenced as a conditional step within the larger workflow.

**Pull request merged**
